- id: osh-addons-table
  name: Generate addons table in README
  always_run: true
  entry: osh-addons-table
  language: python
  pass_filenames: false

- id: osh-man-fix
  name: Fix the manifest
  entry: osh-man-fix
  pass_filenames: false
  language: python
  files: (__manifest__\.py|__openerp__\.py|__terp__\.py)$

